# Updates each motd.txt to include active review threads from the forums automagically
name: Auto Trialmin Review Threads
on:
  schedule:
    - cron: 0 0,6,12,18 * * *
  workflow_dispatch:

jobs:
  auto_review_threads:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install node-html-parser@7.1.0
      - name: Include trialmin review threads
        uses: actions/github-script@v9
        with:
          script: |
            const makeReviewThreads = require('${{ github.workspace }}/.github/workflows/autoReviewThreads.js');
            await makeReviewThreads({ glob });
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.CI_BOT_CLIENT_ID }}
          private-key: ${{ secrets.CI_BOT_PRIVATE_KEY }}
      - name: Merge changes
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add '**/motd.txt'
          if [[ ! -z $(git diff --cached) ]]; then git commit -m "update trialmin threads list in motd.txt"; git push; fi
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}